FROM python:3.12-slim-bookworm

ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl unzip nodejs npm

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PORT 3000

CMD reflex run --env prod --frontend-only --frontend-port ${PORT}