FROM python:3.12-slim-bookworm

# by Python nie buforował stdout i stderr
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y curl unzip

# TODO: zmienić na uv
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PORT 8000

CMD reflex run --env prod --backend-only --backend-port ${PORT}